### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by aemxn** [faizanayubi/AMTracker#1]
Hi, thanks for making this in a public domain. But I wonder how the config file looks like? Can you share it?

**Comment by faizanayubi** [comment]
Hi, @aimanbaharum this is just old files of @vNative Tracking system. I don't remember the config file. May I know what are you trying to Build so I can help.

**Comment by aemxn** [comment]
Ah, that's fine then. I'm just trying to learn how AM works and find yours are simple to use but missing the config file when trying to run it. Not a problem.

Thanks for responding though 😃
